"""create fundamentals statement tables

Revision ID: 7dd7403eedf1
Revises: 
Create Date: 2026-08-11 19:51:56.927569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dd7403eedf1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_sheets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('reported_at', sa.Date(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('total_assets', sa.Float(), nullable=True),
    sa.Column('total_debt', sa.Float(), nullable=True),
    sa.Column('cash_and_equivalents', sa.Float(), nullable=True),
    sa.Column('minority_interest', sa.Float(), nullable=True),
    sa.Column('minority_interest_known', sa.Boolean(), nullable=False),
    sa.Column('preferred_equity', sa.Float(), nullable=True),
    sa.Column('preferred_equity_known', sa.Boolean(), nullable=False),
    sa.Column('book_equity', sa.Float(), nullable=True),
    sa.Column('goodwill', sa.Float(), nullable=True),
    sa.Column('inventory', sa.Float(), nullable=True),
    sa.Column('receivables', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'period_end', 'source', 'reported_at', name='uq_balance_sheet_vintage')
    )
    op.create_index('ix_balance_sheets_ticker_available', 'balance_sheets', ['ticker', 'available_at'], unique=False)
    op.create_index('ix_balance_sheets_ticker_period_available', 'balance_sheets', ['ticker', 'period_end', 'available_at'], unique=False)
    op.create_table('cash_flow_statements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('reported_at', sa.Date(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('operating_cash_flow', sa.Float(), nullable=True),
    sa.Column('depreciation_amortization', sa.Float(), nullable=True),
    sa.Column('capex', sa.Float(), nullable=True),
    sa.Column('delta_working_capital', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'period_end', 'source', 'reported_at', name='uq_cash_flow_statement_vintage')
    )
    op.create_index('ix_cash_flow_statements_ticker_available', 'cash_flow_statements', ['ticker', 'available_at'], unique=False)
    op.create_index('ix_cash_flow_statements_ticker_period_available', 'cash_flow_statements', ['ticker', 'period_end', 'available_at'], unique=False)
    op.create_table('income_statements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('reported_at', sa.Date(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('cogs', sa.Float(), nullable=True),
    sa.Column('operating_expenses', sa.Float(), nullable=True),
    sa.Column('net_income', sa.Float(), nullable=True),
    sa.Column('diluted_shares_outstanding', sa.Float(), nullable=True),
    sa.Column('interest_expense', sa.Float(), nullable=True),
    sa.Column('ebit', sa.Float(), nullable=True),
    sa.Column('stock_based_compensation', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'period_end', 'source', 'reported_at', name='uq_income_statement_vintage')
    )
    op.create_index('ix_income_statements_ticker_available', 'income_statements', ['ticker', 'available_at'], unique=False)
    op.create_index('ix_income_statements_ticker_period_available', 'income_statements', ['ticker', 'period_end', 'available_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_income_statements_ticker_period_available', table_name='income_statements')
    op.drop_index('ix_income_statements_ticker_available', table_name='income_statements')
    op.drop_table('income_statements')
    op.drop_index('ix_cash_flow_statements_ticker_period_available', table_name='cash_flow_statements')
    op.drop_index('ix_cash_flow_statements_ticker_available', table_name='cash_flow_statements')
    op.drop_table('cash_flow_statements')
    op.drop_index('ix_balance_sheets_ticker_period_available', table_name='balance_sheets')
    op.drop_index('ix_balance_sheets_ticker_available', table_name='balance_sheets')
    op.drop_table('balance_sheets')
    # ### end Alembic commands ###
