"""create price bars table

Revision ID: bc47a11def4d
Revises: 7dd7403eedf1
Create Date: 2026-08-11 23:39:32.182270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc47a11def4d'
down_revision: Union[str, Sequence[str], None] = '7dd7403eedf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_bars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('ts', sa.Date(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'ts', 'source', 'available_at', name='uq_price_bar_vintage')
    )
    op.create_index('ix_price_bars_ticker_available', 'price_bars', ['ticker', 'available_at'], unique=False)
    op.create_index('ix_price_bars_ticker_ts_available', 'price_bars', ['ticker', 'ts', 'available_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_price_bars_ticker_ts_available', table_name='price_bars')
    op.drop_index('ix_price_bars_ticker_available', table_name='price_bars')
    op.drop_table('price_bars')
    # ### end Alembic commands ###
